# Generated by Django 4.2.4 on 2023-10-07 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit_lemon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='description',
            field=models.CharField(default='None', max_length=1000),
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(default='littleLemon2.jpg', upload_to='menu_images/'),
        ),
    ]
